config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to:  'homes#top'


  resources :users do
    resource :relation
    get "followings" => "relations#followings"
    get "followers" => "relations#followers"
  end

  resources :posts do
    resources :post_comments
    resource :favorite do
      collection do
        get :index
      end
    end
  end

  resources :groups do
    member do
      post :join
      delete :out
    end
    resource :group_chat
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord


  belongs_to :user
  belongs_to :post

end

app/models/group.rb
class Group < ApplicationRecord

  has_many :group_users,dependent: :destroy
  has_many :users,through: :group_users

  has_many :group_chats,dependent: :destroy
  has_many :users,through: :group_chats

  attachment :icon_image

end

app/models/group_chat.rb
class GroupChat < ApplicationRecord

  attachment :image

  belongs_to :user
  belongs_to :group


end

app/models/group_user.rb
class GroupUser < ApplicationRecord

  belongs_to :user
  belongs_to :group

end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  has_many :post_comments,dependent: :destroy
  has_many :favorites,dependent: :destroy


  attachment :post_image

end

app/models/post_comment.rb
class PostComment < ApplicationRecord

  belongs_to :user
  belongs_to :post

end

app/models/relation.rb
class Relation < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :posts,dependent: :destroy
  has_many :post_commnets,dependent: :destroy
  has_many :favorites,dependent: :destroy



  has_many :relations,class_name: "Relation",foreign_key: "follower_id",dependent: :destroy
  has_many :followings,through: :relations,source: :followed

  has_many :reverse_of_relations,class_name: "Relation",foreign_key: "followed_id",dependent: :destroy
  has_many :followers,through: :reverse_of_relations,source: :follower

  has_many :group_users,dependent: :destroy
  has_many :groups,through: :group_users

  has_many :group_chats,dependent: :destroy
  has_many :group,through: :group_chats



end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def new
    @group = Group.new
  end

  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
    @group_users = GroupUser.where(group_id: @group.id)
    @group_user = GroupUser.new
  end

  def create
    group = Group.new(group_params)
    group.save
    redirect_to group_path(group.id)
  end

  def edit
    @group = Group.find(params[:id])
  end

  def updatr
    group = Group.update(group_params)
    redirect_to group_path(group.id)
  end

  def destroy
    group = Group.find(params[:id])
    group.destroy
  end


  def join
    group = Group.find(params[:id])
    group_user = GroupUser.new(user_id: current_user.id,group_id: group.id)
    group_user.save
    redirect_to request.referer
  end

  def out
    group = Group.find(params[:id])
    group_user = GroupUser.find_by(user_id: current_user.id,group_id: group.id)
    group_user.destroy
    redirect_to request.referer
  end

  private

  def group_params
    params.require(:group).permit(:name,:icon_image,:caption)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
    @posts = Post.all
  end

  def index
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    def new
      @post = Post.new
    end

    def index
      @q = Post.ransack(params[:q])
      @posts = @q.result(distinic: true)
    end

    def show
      @post = Post.find(params[:id])
      @post_comment = PostComment.new
    end

    def create
      post = Post.new(post_params)
      post.user_id = current_user.id
      if post.save
        redirect_to posts_path
      else
        render new_post_path
      end
    end

    def edit
      @post = Post.find(params[:id])
    end

    def update
      post = Post.find(params[:id])
      if post.update(post_params)
        redirect_to posts_path
      else
        render edit_post_path(post.id)
      end
    end

    def destroy
      @post = Post.find(params[:id])
      @post.destroy
      redirect_to posts_path

    end

    private
    def post_params
        params.require(:post).permit(:caption,:post_image)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name,:email,:profile_image,:introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/group_chats_helper.rb
module GroupChatsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relations_helper.rb
module RelationsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/groups/edit.html.erb
<h1>グループ変更</h1>
<%= form_with model:@group ,local:true do |f| %>
  <h3>グループ名</h3>
  <%= f.text_field :name %>
  <%= f.text_area :caption %>
  <%= f.attachment_field :icon_image %>
  <%= f.submit "変更" %>
<% end %>

app/views/groups/index.html.erb
<h1>グループ一覧</h1>
<% @groups.each do |group| %>
  <%= link_to group_path(group.id) do %>
    <%= group.name %>
  <% end %>
  <%= link_to "グループ削除",group_path(group.id),method: :delete %>
<% end %>

app/views/groups/new.html.erb
<h1>グループ作成</h1>
<%= form_with model: @group,local:true do |f| %>
  <h3>グループ名</h3>
  <%= f.text_field :name %>
  <%= f.text_area :caption %>
  <%= f.submit "作成" %>
<% end %>

app/views/groups/show.html.erb
<h1>グループ</h1>
<%= attachment_image_tag @group,:icon_image,size: "30x30" %>
<%= @group.name %>
<%= @group.caption %>

<h3>メンバー</h3>
<% @group_users.each do |group_user| %>
  <%= attachment_image_tag group_user.user,:profile_image,size: "20x20" %>
  <%= group_user.user.name %>
<% end %>

<% if GroupUser.find_by(user_id: current_user.id,group_id: @group.id) %>
  <%= link_to "グループチャットを始める",new_group_group_chat_path(@group.id) %>
  <%= link_to "グループを退会する",out_group_path(@group.id) ,method: :delete %>
<% else %>
  <%= link_to "グループに参加する",join_group_path(@group.id),method: :post %>
<% end %>


<%= link_to "グループ削除",group_path(@group.id),method: :delete %>

app/views/posts/edit.html.erb
<h2>投稿編集画面</h2>
<%= form_with model: @post ,local:true do |f| %>
  <%= f.attachment_field :post_image %>
  <%= f.text_area :caption %>
  <%= f.submit "更新" %>
<% end %>

app/views/posts/index.html.erb
<%= search_form_for @q do |f| %>
  <h4>キーワード検索</h4>
  <%= f.search_field :caption_cont %>
  <%= f.submit "検索" %>
<% end %>


<h1>投稿一覧</h1>
<% @posts.each do |post| %>
  <%= attachment_image_tag post,:post_image,size: "100x100" %>
  <%= attachment_image_tag post.user,:profile_image,size: "50x50" %>
  <h3>投稿ユーザー</h3>
  <%= post.user.name %>
  <%= post.caption %>

  <% if post.user == current_user %>
    <%= link_to "投稿編集",edit_post_path(post.id) %>
    <%= link_to "投稿削除",post_path(post.id),method: :delete %>
  <% end %>

  <div id= "favorite_btn_<%= post.id %>" >
    <%= render "favorites/favorite" ,post: post %>
  </div>

  <%= link_to post_path(post.id) do %>
    <h4>コメントする</h4>
  <% end %>
  <p>コメント数<%= post.post_comments.count %>件</p>

<% end %>

<%= link_to "新規投稿",new_post_path %>

app/views/posts/new.html.erb
<h2>新規投稿</h2>

<%= form_with model: @post,local:true do |f| %>
  <h3>画像</h3>
  <%= f.attachment_field :post_image %>
  <h3>コメント</h3>
  <%= f.text_area :caption %>
  <%= f.submit "投稿" %>
<% end %>

<%= link_to "投稿一覧",posts_path %>

app/views/posts/show.html.erb
<h3>コメント</h3>
  <% @post.post_comments.each do |post_comment|%>
    <%= post_comment.comment %>
    <p>コメントユーザー</p>
    <%= attachment_image_tag post_comment.user,:profile_image,size: "20x20" %>
    <%= post_comment.user.name %>
    <% if post_comment.user == current_user %>
      <%= link_to "削除",post_post_comment_path(@post.id,post_comment.id),method: :delete %>
    <% end %>
  <% end %>


<h4>コメントフォーム</h4>
<%= form_with(model:[@post,@post_comment],local:true) do |f| %>
  <%= f.text_area :comment %>
  <%= f.submit "コメント送信"%>
<% end %>

  <%= link_to "投稿一覧",posts_path %>

app/views/users/edit.html.erb
<h2>プロフィール編集</h2>
<%= form_with model: @user,url: user_path(@user.id),local:true do |f| %>
  <h3>プロフィール画像</h3>
  <%= f.attachment_field :profile_image %>
  <h3>ユーザー名</h3>
  <%= f.text_field :name %>
  <h3>自己紹介</h3>
  <%= f.text_area :introduction %>
  <%= f.submit "変更" %>
<% end %>

app/views/users/show.html.erb
<div class="main">
  <div class="profile-area">
    <div class="author-profile_image">
      <%= attachment_image_tag @user, :profile_image,format: 'jpeg', fallback: "no-image-icon.jpg",size: "110x110" %>
    </div>
    <h3 class="user-name">
      <%= @user.name%>
    </h3>
    <p class="user-introduction">
      <%= @user.introduction %>
    </p>
  </div>
  <%=link_to edit_user_path(@user.id) do %>
    <div class="edit-icon">
      <i class="fas fa-cog"></i>
    </div>
  <% end %>
</div>

<%= link_to "フォロワー",user_followers_path(@user.id) %>
<%= link_to "フォロー中",user_followings_path(@user.id) %>


<% unless current_user == @user %>
  <% if Relation.find_by(followed_id: @user.id) %>
    <%= link_to "フォローをやめる",user_relation_path(@user.id),method: :delete %>
  <% else %>
    <%= link_to "フォローする",user_relation_path(@user.id),method: :post %>
  <% end %>
<% end %>


<%= link_to "新規投稿",new_post_path %>
<%= link_to "グループ作成",new_group_path %>
<%= link_to "グループ一覧",groups_path %>